spring:
  datasource:
    url: jdbc:mysql:///weixin?useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: HTML
    cache: false
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        format-sql: true
server:
  tomcat:
    basedir: target/
  access_log_enabled: true
